SPN으로부터 Pitch class를 생성하는 방법을 추가합니다.
binarysound/colorado pull request #12
Opened 2018-02-09 10:49 UTC by limgit

이슈 #9 와 관련된 PR입니다.

당시 해당 이슈에서, `new Pitch('A4')`의 형태를 갖는 것이 낫다고 생각했는데, JS의 특징상 생성자 오버로딩이 쉽지 않아서 static factory method인 `fromSPN`을 만드는 쪽으로 방향을 선회했습니다.

본 PR의 변경 사항은 다음과 같습니다.
  - `Pitch` class에 static helper method인 `isValidSPN`을 추가했습니다.
      - 해당 함수는 인자로 받은 string이 SPN에 적합한 form인지 확인하고 그 결과를 boolean으로 return합니다. 주의해야 할 점은, C4는 SPN이지만 C는 SPN이 아니라는 것입니다. (Wikipedia의 [SPN 문서](https://en.wikipedia.org/wiki/Scientific_pitch_notation) 참고)
  - `Pitch` class에 static factory method인 `fromSPN`을 추가했습니다.
      - 해당 함수는 인자로 받은 SPN 값을 파싱하여 적절한 height를 지닌 `Pitch` object를 리턴합니다. 인자로 주어진 것이 적합하지 않으면 에러를 던집니다.

비고
  - SPN과 관련된 모든 내용은 12 tone just intonation 혹은 12 tone equal temperament가 가정되었을때만 유의미합니다. 그러나 `Pitch` object는 그저 단순히 '해당 pitch가 concert pitch를 기준으로 몇 단위 음에 위치하는가'의 정보만을 기록하기 때문에 tuning system과는 완전히 독립적입니다. 이는 곧 12-TET나 12-TJI (편의상 이렇게 기록하겠습니다) 가 아닌 Tuning system상에서 SPN을 이용해 생성한 `Pitch` object를 사용할 수 있다는 뜻도 되는데요, 이는 라이브러리에서 검사를 해 거르는 것이 아닌, 유저가 주의해서 사용해야 하는 부분으로 남겨둬야 할까요?

2018-02-09 11:11 UTC, JeongHoJeong requested changes
👍

2018-02-09 11:11 UTC, JeongHoJeong commented on src/pitch.ts
> +    const spnRegex = /^([A-G](#|b)?)(-?([1-9][0-9]+|[0-9]))$/
[5번 줄에 있는 regex](https://github.com/binarysound/colorado/pull/12/files#diff-7f3168ca19ce6f737f0ecb5e5c136187R5)와 grouping만 빼고는 똑같은 것 같은데요, 상수로 할당해 통일해 쓸 수는 없을까요?

2018-02-09 11:11 UTC, JeongHoJeong commented on src/pitch.ts
> +    height = height + 12 * (parseInt(match[3], 10) - 4)
1. 주석은 없어도 코드가 이미 뜻을 잘 설명하고 있는 것 같습니다. 단, `match[1]`이나 `match[3]`는 미리 알아보기 쉬운 `const` 값으로 따오면 가독성이 높아질 것 같습니다.
2. `height`에 대한 2회 이상의 재할당과 `switch`가 마음에 걸리는데요, 가능하면 `const`로 전부 처리하고 싶은 마음이 있습니다. object literal을 사용하는 것은 어떻게 생각하시나요?

```ts
const pitchClassToHeightMap = {
  'A': 0,
  'A#': 0,
  'Bb': 1,
  /* ... */
}

/* ... */

export default class Pitch {
 
  /* ... */

  public static fromSPN(spn: string): Pitch {

    /* ... */

    const pitchClass = match[1]
    const octave = match[3]

    const octaveOffset = parseInt(octave, 10) - 4
    const height = pitchClassToHeightMap[pitchClass] + 12 * octave

    return new Pitch(height)
  }

  /* ... */

}
```

`switch`에 대한 제 견해는 [이 글(Rethinking JavaScript: Eliminate the switch statement for better code)](https://hackernoon.com/rethinking-javascript-eliminate-the-switch-statement-for-better-code-5c81c044716d)이 뒷받침해줄 것 같습니다.

2018-02-09 11:11 UTC, JeongHoJeong commented on src/pitch.ts
> +    const spnRegex = /^([A-G](#|b)?)(-?([1-9][0-9]+|[0-9]))$/
또, 꼭 대문자인 경우만 고려해야 할까요? 소문자인 경우도 너그럽게 처리해주는 것은 어떻게 생각하시나요?

2018-02-09 11:11 UTC, JeongHoJeong commented on src/pitch.spec.ts
> +    expect(Pitch.isValidSPN('c')).toBe(false)
밑 코멘트와 비슷한 맥락에서, `c3` 등 소문자 노테이션에 대한 테스트도 하나정도는 있으면 좋겠습니다.

2018-02-09 11:16 UTC, JeongHoJeong commented
비고 1에 관하여는, SPN의 정의 자체가 옥타브를 12개 톤으로 나눈 것을 가정한 상태에서의 pitch naming이기 때문에 유저가 주의할 것이 맞는 것 같습니다. `fromSPN`에 코멘트로 SPN의 개념에 대한 권위 있는 저술을 링크하는 것은 어떻게 생각하시나요?

2018-02-10 04:16 UTC, limgit commented on src/pitch.ts
> +    const spnRegex = /^([A-G](#|b)?)(-?([1-9][0-9]+|[0-9]))$/
음.... 처음에 그렇게 생각해서 동일하게 쓰려다가 grouping이 달라서 통일 못하겠네... 싶어서 놔둔거였습니다. 지금 보니 동일하게 써도 문제 없을거같네요. grouping이 matching에 직접 영향을 주진 않으니까요 :)

소문자 처리는 그냥 이 라이브러리의 재량으로 맡겨도 괜찮은 부분인 것 같습니다. 처리하도록 할까요?

2018-02-10 04:19 UTC, limgit commented on src/pitch.ts
> +    height = height + 12 * (parseInt(match[3], 10) - 4)
1. 사실 `match[1]`과 `match[3]`가 의미가 직관적이지 않아서 주석을 삽입한 부분이었습니다. 그런데 그냥 const로 따오면서 변수 이름을 잘 지으면 되는 문제였네요 :)

2. 가능한 `const`만 써보고자 하다가 마땅히 생각나는 것이 없어 `switch`로 대체해둔 참이었습니다. 근데 `map`의 형태를 이용할 수 있단걸 생각을 못했네요 :sob:

2018-02-10 04:24 UTC, limgit commented on src/pitch.ts
> +    const spnRegex = /^([A-G](#|b)?)(-?([1-9][0-9]+|[0-9]))$/
음 생각해보니 [Helmhortz pitch notation](https://en.wikipedia.org/wiki/Helmholtz_pitch_notation)에서는 대소문자 구분이 중요한 문제긴 하네요... SPN이 HPN과 연관되어서 언급되는 일이 잦은걸 봤을 때는 소문자를 허용하지 않아야 할 것 같기도 합니다

2018-02-10 06:05 UTC, limgit commented
괜찮네요. 권위있는 저술이라.... [Wikipedia의 문서](https://en.wikipedia.org/wiki/Scientific_pitch_notation) 정도면 적당하려나요? 절대적인 공신력과 권위가 있는 문서는 아니지만, 우리 목적에서는 저정도로도 충분할 것 같아요.

2018-02-10 06:12 UTC, JeongHoJeong commented
우리 목적에서는 위키 링크도 괜찮은 것 같습니다. 굿.

2018-02-10 06:20 UTC, JeongHoJeong commented on src/pitch.ts
> +    const spnRegex = /^([A-G](#|b)?)(-?([1-9][0-9]+|[0-9]))$/
그렇네요. SPN에 관한 저술 그 어디도 소문자를 쓰지 않는다는 점에서 암묵적 규칙으로 봐야 할 듯도 합니다. 말씀하신 Helmhortz pitch notation과의 구별을 위해서라도 대문자만 받는 게 지금은 안전하겠군요.

http://www.dolmetsch.com/musictheory1.htm#uspitch

2018-02-12 01:54 UTC, limgit commented
리뷰 반영했습니다.
 - 모든 변수를 `const`로 변경
 - 소문자 표기에 대한 테스트 하나 추가
 - `fromSPN` 함수에 주석 추가

2018-02-12 05:02 UTC, limgit commented on src/pitch.ts
> +const heightOfPitchClass = {
linter가 alphabetically ordered를 요구해서 이렇게 작성하긴 했는데 린팅 예외 처리하고 Cb, C, C#, Db, D, D#, ..., Bb, B, B# 순으로 바꾸는 것이 나을까요? 어떻게 생각하시나요

2018-02-12 05:02 UTC, limgit commented on src/pitch.ts
> +  'Gb': -3,
linter가 alphabetically ordered를 요구해서 이렇게 작성하긴 했는데 린팅 예외 처리하고 Cb, C, C#, Db, D, D#, ..., Bb, B, B# 순으로 바꾸는 것이 나을까요? 어떻게 생각하시나요

2018-02-12 08:07 UTC, JeongHoJeong commented on src/pitch.ts
> +  'Gb': -3,
아ㅋㅋㅋㅋ 거기서 린터가... 예외처리하고 음 순서대로 하시는 편이 맞겠습니다.

[object-literal-sort-keys](https://palantir.github.io/tslint/rules/object-literal-sort-keys/)를 일시적으로 꺼야겠군요.

```
/* tslint:disable:object-literal-sort-keys */
```

2018-02-12 08:09 UTC, JeongHoJeong commented
@limgit 네, 지워주시면 감사하겠습니다!

2018-02-12 08:52 UTC, JeongHoJeong approved these changes

2018-02-12 08:56 UTC, merged