Pitch 클래스를 추가합니다.
binarysound/colorado pull request #8
Opened 2018-02-07 17:37 UTC by JeongHoJeong

`Pitch` 클래스와 그에 관련된 간단한 몇가지 함수들을 구현합니다.

## 구현한 함수들
- `getFrequency`
- `getMidi`

2018-02-08 03:23 UTC, limgit requested changes
두가지 코멘트 달았습니다. 확인해주세요.

2018-02-08 03:23 UTC, limgit commented on src/pitch.ts
> +  constructor(height: number = 0) {
그냥 개인적인 생각이긴 한데, 이부분에서 height 값을 default argument를 주지 않는 편이 낫지 않을까요? 사용자가 명시하지 않으면 에러를 뱉도록 하는게 나을 것 같아서요.

2018-02-08 03:23 UTC, limgit commented on src/tuning-system.ts
> +      throw new ColoradoError(
이전에 미디에서 미세음정 조정에 관한 말씀을 해주셨던 기억이 있는데, 이부분은 일단 예외처리로 두고 후에 구현할 예정이신가요? 그렇다면 `// TODO` 주석을 삽입해두는 것이 낫겠습니다.

2018-02-08 04:36 UTC, JeongHoJeong commented on src/tuning-system.ts
> +      throw new ColoradoError(
음.. 이 함수를 만든 이유는 일반적인 미디 노트 넘버를 반환하게 하려는 목적이었긴 한데, 그럼 함수 설명을 보완하거나 이름을 바꿔야겠군요.

2018-02-08 04:44 UTC, JeongHoJeong commented on src/tuning-system.ts
> +      throw new ColoradoError(
확장에 대비하자는 것도 동의합니다. 좋은 지적 굿굿 ☺️

2018-02-08 20:51 UTC, JeongHoJeong commented
@limgit 리뷰 반영했습니다.

2018-02-09 03:07 UTC, limgit approved these changes
LGTM!

2018-02-09 03:37 UTC, merged